export interface Product {
    id: string;
    name: string;
    shortDescription: string;
    idealUser: string;
    rating: number;
    pros: string[];
    price: string;
    priceRange: string;
    type: "Automatic" | "Semi-automatic" | "Manual" | "Capsule" | "Drip";
    milkFrother: boolean;
    capacity: string;
    bestFor: string;
    easeOfUse: string;
    // Advanced Technical Metrics
    pumpPressure?: string;
    grinder?: string;
    heatingSystem?: string;
    programmability?: string;
    image: string;
    latestPriceLink: string;
}

export const products: Product[] = [
    {
        id: "breville-barista-touch-impress",
        name: "Breville Barista Touch Impress",
        shortDescription: "Experience third wave specialty coffee at home with the Barista Touch Impress. Featuring a touch screen, automatic grinding, and assisted tamping for a professional-grade espresso every time.",
        idealUser: "Aspiring Home Baristas",
        rating: 4.9,
        pros: ["Step-by-step barista guidance", "Assisted tamping with 7-degree twist", "Auto MilQ hands-free milk texturing"],
        price: "$1,499.95",
        priceRange: "$$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.0L",
        bestFor: "Espresso Quality",
        easeOfUse: "Guided",
        pumpPressure: "15 Bar",
        grinder: "Conical Burr",
        heatingSystem: "ThermoJet",
        image: "https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0C3MQHBNH",
    },
    {
        id: "delonghi-magnifica-evo",
        name: "De'Longhi Magnifica Evo",
        shortDescription: "A fully automatic espresso machine that brings the authentic Italian espresso experience to your kitchen. Features 7 one-touch recipes and a built-in conical burr grinder.",
        idealUser: "Convenience Seekers",
        rating: 4.7,
        pros: ["One-touch milk recipes", "Built-in 13-setting grinder", "Easy cleaning with dishwasher-safe parts"],
        price: "$799.95",
        priceRange: "$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "1.8L",
        bestFor: "Lattes & Cappuccinos",
        easeOfUse: "Very Easy",
        pumpPressure: "15 Bar",
        grinder: "Steel Burr",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1544787210-282743207b5b?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B09V1L9X6Z",
    },
    {
        id: "ninja-dualbrew-pro",
        name: "Ninja DualBrew Pro System",
        shortDescription: "Unlock the ultimate capability with the DualBrew Pro. Brew grounds or pods, and choose from 4 brew styles: Classic, Rich, Over Ice, or Specialty.",
        idealUser: "Versatile Coffee Drinkers",
        rating: 4.6,
        pros: ["Grounds and pods compatibility", "Built-in fold-away frother", "Independent hot water system"],
        price: "$229.99",
        priceRange: "$$",
        type: "Drip",
        milkFrother: true,
        capacity: "60 oz",
        bestFor: "Variety",
        easeOfUse: "Easy",
        pumpPressure: "None",
        grinder: "None",
        heatingSystem: "Thermal",
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B097Z7N9KF",
    },
    {
        id: "breville-barista-express",
        name: "Breville Barista Express",
        shortDescription: "The iconic all-in-one espresso machine. Grind, dose, and extract with precision. The perfect start for those wanting control over their espresso journey.",
        idealUser: "Hands-on Enthusiasts",
        rating: 4.8,
        pros: ["Integrated conical burr grinder", "Precision milk texturing", "Analog pressure gauge"],
        price: "$699.95",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.0L",
        bestFor: "Skill Development",
        easeOfUse: "Intermediate",
        pumpPressure: "15 Bar",
        grinder: "Conical Burr",
        heatingSystem: "Thermocoil",
        image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B00CH9QWOU",
    },
    {
        id: "ninja-12-cup-programmable",
        name: "Ninja 12-Cup Programmable Brewer",
        shortDescription: "High-quality coffee in a large capacity. Custom brew strengths and a Thermal Flavor Extraction technology ensure a rich, full-bodied cup every time.",
        idealUser: "Families and Social Hosts",
        rating: 4.5,
        pros: ["Advanced Thermal Flavor Extraction", "24-hour programmable delay brew", "Mid-brew pause function"],
        price: "$89.99",
        priceRange: "$",
        type: "Drip",
        milkFrother: false,
        capacity: "12 Cups",
        bestFor: "Large Batches",
        easeOfUse: "Very Easy",
        pumpPressure: "N/A",
        grinder: "None",
        heatingSystem: "Thermal Extraction",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07S98411M",
    },
    {
        id: "delonghi-dedica-maestro-plus",
        name: "De'Longhi Dedica Maestro Plus",
        shortDescription: "Professional style in a compact design. The Dedica Maestro Plus offers a premium espresso experience for those with limited counter space.",
        idealUser: "Urban Professionals",
        rating: 4.6,
        pros: ["Compact 6-inch footprint", "My LatteArt steam wand", "Active temperature control"],
        price: "$299.95",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.1L",
        bestFor: "Small Kitchens",
        easeOfUse: "Intermediate",
        pumpPressure: "15 Bar",
        grinder: "None",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1517701550927-30cfcb61d4bd?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0CDY85Q2N",
    },
    {
        id: "philips-5400-series",
        name: "Philips 5400 Series Automatic Espresso",
        shortDescription: "Enjoy 12 delicious coffees from fresh beans, including Latte Macchiato, effortlessly. The LatteGo system provides silky-smooth milk froth.",
        idealUser: "Variety Lovers",
        rating: 4.7,
        pros: ["LatteGo easiest milk system ever", "12 coffee varieties at your fingertips", "4 user profiles for personalization"],
        price: "$999.00",
        priceRange: "$$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "1.8L",
        bestFor: "User Customization",
        easeOfUse: "Very Easy",
        pumpPressure: "15 Bar",
        grinder: "Ceramic Burr",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B08V5MDXDM",
    },
    {
        id: "oxo-brew-8-cup",
        name: "OXO Brew 8-Cup Coffee Maker",
        shortDescription: "Certified by the SCA for meeting rigorous gold-cup standards. Simple operation, elegant design, and exceptional extraction quality.",
        idealUser: "Flavor Purists",
        rating: 4.5,
        pros: ["SCA Certified Gold Cup brewing", "BetterBrew precision control", "Single-serve capability"],
        price: "$199.95",
        priceRange: "$$",
        type: "Drip",
        milkFrother: false,
        capacity: "8 Cups",
        bestFor: "Brewing Standards",
        easeOfUse: "Very Easy",
        pumpPressure: "N/A",
        grinder: "None",
        heatingSystem: "Precision Heating",
        image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0892CHRT3",
    },
    {
        id: "keurig-k-elite",
        name: "Keurig K-Elite Coffee Maker",
        shortDescription: "A versatile single-serve machine that offers a strong brew setting and an iced coffee feature for a perfect cup every time.",
        idealUser: "Busy Individuals",
        rating: 4.6,
        pros: ["Strong brew & iced coffee settings", "Large 75oz water reservoir", "Hot water on demand"],
        price: "$189.99",
        priceRange: "$$",
        type: "Capsule",
        milkFrother: false,
        capacity: "75 oz",
        bestFor: "Speed & Convenience",
        easeOfUse: "Very Easy",
        pumpPressure: "N/A",
        grinder: "None",
        heatingSystem: "Internal Tank",
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B078XNWG3N",
    },
    {
        id: "nespresso-vertuoplus",
        name: "Nespresso VertuoPlus by Breville",
        shortDescription: "Utilizes barcode reading technology to automatically adjust brewing parameters for each capsule, ensuring a perfect crema.",
        idealUser: "Espresso Aficionados",
        rating: 4.7,
        pros: ["One-touch brewing system", "Barcode reading for precision", "Adjustable water tank position"],
        price: "$169.00",
        priceRange: "$$",
        type: "Capsule",
        milkFrother: false,
        capacity: "40 oz",
        bestFor: "Rich Crema",
        easeOfUse: "Very Easy",
        pumpPressure: "19 Bar",
        grinder: "None",
        heatingSystem: "Centrifusion",
        image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B01N7T9S77",
    },
    {
        id: "delonghi-la-specialista-arte",
        name: "De'Longhi La Specialista Arte",
        shortDescription: "A compact manual machine that allows you to play the role of the barista with precise control over dose and temperature.",
        idealUser: "Artisan Coffee Lovers",
        rating: 4.8,
        pros: ["Built-in grinder with 8 settings", "Active temperature control", "Professional steam wand"],
        price: "$699.95",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.7L",
        bestFor: "Hands-on Experience",
        easeOfUse: "Intermediate",
        pumpPressure: "15 Bar",
        grinder: "Integrated Burr",
        heatingSystem: "Thermoblock PID",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B09M96V6G2",
    },
    {
        id: "hamilton-beach-flexbrew",
        name: "Hamilton Beach FlexBrew Trio",
        shortDescription: "The ultimate 3-way coffee maker. Brew a full pot, a single cup with grounds, or a single cup with a pod.",
        idealUser: "Budget Conscious Families",
        rating: 4.4,
        pros: ["3-way brewing versatility", "Programmable carafe side", "Fast single-cup brewing"],
        price: "$99.99",
        priceRange: "$",
        type: "Drip",
        milkFrother: false,
        capacity: "12 Cups",
        bestFor: "Affordable Versatility",
        easeOfUse: "Easy",
        pumpPressure: "N/A",
        grinder: "None",
        heatingSystem: "Internal Heating",
        image: "https://images.unsplash.com/photo-1517701550927-30cfcb61d4bd?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07LBCMHG5",
    },
    {
        id: "jura-e8-automatic",
        name: "Jura E8 Automatic Coffee Machine",
        shortDescription: "The latest generation of Jura's most successful model. Features a professional aroma grinder and a stunning 2.8 inch color display.",
        idealUser: "Luxury Enthusiasts",
        rating: 4.9,
        pros: ["Pulse Extraction Process (P.E.P.)", "One-touch Lungo function", "Intelligent Water System (I.W.S.)"],
        price: "$2,399.00",
        priceRange: "$$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "1.9L",
        bestFor: "Premium Quality",
        easeOfUse: "Very Easy",
        pumpPressure: "15 Bar",
        grinder: "Professional Aroma Grinder",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1524350300313-019f39d67d7a?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B08X6K6K5R",
    },
    {
        id: "rancilio-silvia-m",
        name: "Rancilio Silvia M Espresso Machine",
        shortDescription: "A legendary semi-automatic machine built with commercial-grade components. Perfect forThose who want to master the art of traditional espresso.",
        idealUser: "Purists",
        rating: 4.7,
        pros: ["Commercial-grade group head", "Stainless steel case", "Industrial steam wand"],
        price: "$860.00",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.5L",
        bestFor: "Durability",
        easeOfUse: "Expert",
        pumpPressure: "15 Bar",
        grinder: "None",
        heatingSystem: "Single Brass Boiler",
        image: "https://images.unsplash.com/photo-1572442388796-11668a67e53a?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B000109COY",
    },
    {
        id: "gaggia-classic-pro",
        name: "Gaggia Classic Pro",
        shortDescription: "The best entry-level prosumer espresso machine. Features a commercial steam wand and a rapid steam boiler.",
        idealUser: "Budget Baristas",
        rating: 4.6,
        pros: ["Commercial 58mm portafilter", "3-way solenoid valve", "Fast heat-up time"],
        price: "$449.00",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.1L",
        bestFor: "Value",
        easeOfUse: "Intermediate",
        pumpPressure: "15 Bar",
        grinder: "None",
        heatingSystem: "Rapid Steam Boiler",
        image: "https://images.unsplash.com/photo-1580915411954-282cb1b0d780?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07KKC4W8N",
    },
    {
        id: "baratza-encore-esp",
        name: "Baratza Encore ESP",
        shortDescription: "The industry standard grinder for home espresso. Features 40mm conical m3 burrs for precision grind consistency across all brewing methods.",
        idealUser: "Home Barista Beginners",
        rating: 4.8,
        pros: ["High-torque DC motor", "40 grind settings", "Pulse button"],
        price: "$199.95",
        priceRange: "$$",
        type: "Manual",
        milkFrother: false,
        capacity: "8oz Hopper",
        bestFor: "Grind Consistency",
        easeOfUse: "Very Easy",
        pumpPressure: "N/A",
        grinder: "Conical Burr",
        heatingSystem: "N/A",
        image: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0BYBC3B72",
    },
    {
        id: "delonghi-stilosa",
        name: "De'Longhi Stilosa",
        shortDescription: "Sleek and compact 15-bar pump espresso machine for brewing authentic barista-quality beverages.",
        idealUser: "Minimalists",
        rating: 4.3,
        pros: ["15-bar pump", "Contemporary design", "Manual milk frother"],
        price: "$99.95",
        priceRange: "$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.0L",
        bestFor: "Budget Starters",
        easeOfUse: "Easy",
        pumpPressure: "15 Bar",
        grinder: "None",
        heatingSystem: "Stainless Steel Boiler",
        image: "https://images.unsplash.com/photo-1521302080334-4bebac2763a6?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B08C96D692",
    },
    {
        id: "rocket-espresso-apartamento",
        name: "Rocket Espresso Apartamento",
        shortDescription: "A compact espresso machine designed for environments where space is at a premium but quality is mandatory.",
        idealUser: "Space-Conscious Enthusiasts",
        rating: 4.9,
        pros: ["Heat exchange boiler", "Vibratory pump", "Iconic circular cut-outs"],
        price: "$1,850.00",
        priceRange: "$$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.8L",
        bestFor: "Aesthetics & Power",
        easeOfUse: "Advanced",
        pumpPressure: "15 Bar",
        grinder: "None",
        heatingSystem: "Heat Exchange Boiler",
        image: "https://images.unsplash.com/photo-1572442388796-11668a67e53a?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B01MT29C1F",
    },
    {
        id: "la-marzocco-linea-micra",
        name: "La Marzocco Linea Micra",
        shortDescription: "The gold standard of home espresso machines. Commercial-grade performance in a compact kitchen-friendly footprint.",
        idealUser: "Professional Baristas at Home",
        rating: 5.0,
        pros: ["Dual boiler system", "Rotary pump", "Fast heat-up time"],
        price: "$3,900.00",
        priceRange: "$$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.0L",
        bestFor: "Ultimate Performance",
        easeOfUse: "Expert",
        pumpPressure: "9 Bar (Rotary)",
        grinder: "None",
        heatingSystem: "Dual Boiler",
        image: "https://images.unsplash.com/photo-1595434066389-ed6a67a5342a?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://lamarzocco.com/it/en/home-products/linea-micra/",
    },
    {
        id: "breville-oracle-touch",
        name: "Breville The Oracle Touch",
        shortDescription: "Automates the hardest part of espresso. A dual boiler system that grinds, doses, tamps and textures milk automatically.",
        idealUser: "Hands-off Luxury Seekers",
        rating: 4.9,
        pros: ["Auto grind & tamp", "Dual boiler precision", "Micro-foam milk texturing"],
        price: "$2,799.00",
        priceRange: "$$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "2.5L",
        bestFor: "Full Automation",
        easeOfUse: "Very Easy",
        pumpPressure: "15 Bar",
        grinder: "Integrated Conical",
        heatingSystem: "Dual Boiler",
        image: "https://images.unsplash.com/photo-1544787210-282743207b5b?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B078WMLG8X",
    },
    {
        id: "jura-z10-aluminum",
        name: "Jura Z10 Aluminum",
        shortDescription: "A world-first product. Brews both hot and cold specialty coffees at the touch of a button with its Product Recognizing Grinder.",
        idealUser: "High-end Tech Enthusiasts",
        rating: 4.9,
        pros: ["Cold extraction process", "Product Recognizing Grinder", "Vacuum clean technology"],
        price: "$3,999.00",
        priceRange: "$$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "2.4L",
        bestFor: "Cold Brew & Innovation",
        easeOfUse: "One-Touch",
        pumpPressure: "15 Bar",
        grinder: "P.R.G. (Electronic)",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B09D8RVX1W",
    },
    {
        id: "fellow-ode-gen-2",
        name: "Fellow Ode Brew Grinder Gen 2",
        shortDescription: "Award-winning grinder designed for brewed coffee (pour-over, French press, cold brew). Quiet, clean, and incredibly fast.",
        idealUser: "Filter Coffee Purists",
        rating: 4.8,
        pros: ["Professional grade 64mm flat burrs", "New anti-static technology", "Quiet operation"],
        price: "$345.00",
        priceRange: "$$",
        type: "Manual",
        milkFrother: false,
        capacity: "100g Hopper",
        bestFor: "Filter Coffee",
        easeOfUse: "Easy",
        pumpPressure: "N/A",
        grinder: "64mm Flat Burr",
        heatingSystem: "N/A",
        image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0BJLFLN9L",
    },
    {
        id: "kitchenaid-semi-automatic",
        name: "KitchenAid Semi-Automatic Espresso",
        shortDescription: "A reliable and stylish machine designed with dual, smart temperature sensors to maintain the perfect brewing temperature.",
        idealUser: "Kitchen Aesthetics Lovers",
        rating: 4.5,
        pros: ["Dual temperature sensors", "Italian 15-bar pump", "Commercial-grade portafilter"],
        price: "$349.00",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.4L",
        bestFor: "Home Aesthetics",
        easeOfUse: "Intermediate",
        pumpPressure: "15 Bar",
        grinder: "None",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B08VMT1W2S",
    },
    {
        id: "lelit-bianca-v3",
        name: "Lelit Bianca V3",
        shortDescription: "The ultimate machine for coffee nerds. Take full control over water flow with the manual paddle for pressure profiling.",
        idealUser: "Pressure Profiling Experts",
        rating: 4.9,
        pros: ["Manual water flow control", "Dual boiler", "Wooden accents"],
        price: "$2,995.00",
        priceRange: "$$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.5L",
        bestFor: "Pressure Profiling",
        easeOfUse: "Expert",
        pumpPressure: "Active Flow Control",
        grinder: "None",
        heatingSystem: "Dual Boiler",
        image: "https://images.unsplash.com/photo-1572442388796-11668a67e53a?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://lelit.com/product/bianca-pl162t/",
    },
    {
        id: "breville-precision-brewer",
        name: "Breville Precision Brewer",
        shortDescription: "World's first 60oz drip coffee maker with the precision required to brew craft filter coffee automatically.",
        idealUser: "Serious Drip Drinkers",
        rating: 4.7,
        pros: ["PID temperature control", "6 brewing modes", "Gold Cup standard"],
        price: "$329.95",
        priceRange: "$$",
        type: "Drip",
        milkFrother: false,
        capacity: "1.8L",
        bestFor: "Precision Filter",
        easeOfUse: "Easy",
        pumpPressure: "N/A",
        grinder: "None",
        heatingSystem: "Thermoblock PID",
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B078WMLG8X",
    },
    {
        id: "comandante-c40-mk4",
        name: "Comandante C40 MK4 Grinder",
        shortDescription: "The gold standard of manual hand grinders. Incredible grind consistency and built for a lifetime of use.",
        idealUser: "Traveling Baristas",
        rating: 4.9,
        pros: ["Nitro Blade burrs", "Unmatched precision", "No electricity needed"],
        price: "$338.00",
        priceRange: "$$",
        type: "Manual",
        milkFrother: false,
        capacity: "40g",
        bestFor: "Hand Grinding",
        easeOfUse: "Physical Effort",
        pumpPressure: "N/A",
        grinder: "Nitro Blade Conical",
        heatingSystem: "N/A",
        image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B09K825NXP",
    },
    {
        id: "rancilio-silvia-pro-x",
        name: "Rancilio Silvia Pro X",
        shortDescription: "A professional-level dual boiler machine that offers incredible thermal stability and commercial-grade steaming.",
        idealUser: "Performance focused Enthusiasts",
        rating: 4.8,
        pros: ["Dual boiler", "Digital PID controller", "Vibratory pump with soft infusion"],
        price: "$1,875.00",
        priceRange: "$$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.5L",
        bestFor: "Consistency",
        easeOfUse: "Expert",
        pumpPressure: "Vibratory (Self-Priming)",
        grinder: "None",
        heatingSystem: "Dual Boiler PID",
        image: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B09M7N6P6W",
    },
    {
        id: "jura-ena-8-metropolitan",
        name: "Jura ENA 8 Metropolitan Black",
        shortDescription: "Compact, stunning, and simple. One-touch automatic coffee machine for the modern urban apartment.",
        idealUser: "Chic Apartment Dwellers",
        rating: 4.7,
        pros: ["Stunning cylindrical water tank", "Small footprint", "Pulse Extraction Process"],
        price: "$1,899.00",
        priceRange: "$$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "1.1L",
        bestFor: "Compact Luxury",
        easeOfUse: "One-Touch",
        pumpPressure: "15 Bar",
        grinder: "Aroma G3 Grinder",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07P7N5JNR",
    },
    {
        id: "beville-bambino-plus",
        name: "Breville Bambino Plus",
        shortDescription: "Big performance in a small machine. Features automatic milk temperature and texture selection for professional results.",
        idealUser: "Entry Baristas",
        rating: 4.7,
        pros: ["3 second heat up", "Automatic milk texturing", "54mm portafilter"],
        price: "$499.95",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.9L",
        bestFor: "Ease & Quality",
        easeOfUse: "Easy",
        pumpPressure: "15 Bar",
        grinder: "None",
        heatingSystem: "ThermoJet",
        image: "https://images.unsplash.com/photo-1544787210-282743207b5b?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07FKG6PGV",
    },
];
