export interface Product {
    id: string;
    name: string;
    shortDescription: string;
    idealUser: string;
    rating: number;
    pros: string[];
    price: string;
    priceRange: string;
    type: "Automatic" | "Semi-automatic" | "Manual" | "Capsule" | "Drip";
    milkFrother: boolean;
    capacity: string;
    bestFor: string;
    easeOfUse: string;
    // Advanced Technical Metrics
    pumpPressure?: string;
    grinder?: string;
    heatingSystem?: string;
    programmability?: string;
    image: string;
    latestPriceLink: string;
}

export const products: Product[] = [
    {
        id: "breville-barista-touch-impress",
        name: "Breville Barista Touch Impress",
        shortDescription: "Experience third wave specialty coffee at home with the Barista Touch Impress. Featuring a touch screen, automatic grinding, and assisted tamping for a professional-grade espresso every time.",
        idealUser: "Aspiring Home Baristas",
        rating: 4.9,
        pros: ["Step-by-step barista guidance", "Assisted tamping with 7-degree twist", "Auto MilQ hands-free milk texturing"],
        price: "$1,499.95",
        priceRange: "$$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.0L",
        bestFor: "Espresso Quality",
        easeOfUse: "Guided",
        pumpPressure: "15 Bar",
        grinder: "Conical Burr",
        heatingSystem: "ThermoJet",
        image: "https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0C3MQHBNH",
    },
    {
        id: "delonghi-magnifica-evo",
        name: "De'Longhi Magnifica Evo",
        shortDescription: "A fully automatic espresso machine that brings the authentic Italian espresso experience to your kitchen. Features 7 one-touch recipes and a built-in conical burr grinder.",
        idealUser: "Convenience Seekers",
        rating: 4.7,
        pros: ["One-touch milk recipes", "Built-in 13-setting grinder", "Easy cleaning with dishwasher-safe parts"],
        price: "$799.95",
        priceRange: "$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "1.8L",
        bestFor: "Lattes & Cappuccinos",
        easeOfUse: "Very Easy",
        pumpPressure: "15 Bar",
        grinder: "Steel Burr",
        heatingSystem: "Thermoblock",
        image: "https://images.unsplash.com/photo-1544787210-282743207b5b?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B09V1L9X6Z",
    },
    {
        id: "ninja-dualbrew-pro",
        name: "Ninja DualBrew Pro System",
        shortDescription: "Unlock the ultimate capability with the DualBrew Pro. Brew grounds or pods, and choose from 4 brew styles: Classic, Rich, Over Ice, or Specialty.",
        idealUser: "Versatile Coffee Drinkers",
        rating: 4.6,
        pros: ["Grounds and pods compatibility", "Built-in fold-away frother", "Independent hot water system"],
        price: "$229.99",
        priceRange: "$$",
        type: "Drip",
        milkFrother: true,
        capacity: "60 oz",
        bestFor: "Variety",
        easeOfUse: "Easy",
        pumpPressure: "None",
        grinder: "None",
        heatingSystem: "Thermal",
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B097Z7N9KF",
    },
    {
        id: "breville-barista-express",
        name: "Breville Barista Express",
        shortDescription: "The iconic all-in-one espresso machine. Grind, dose, and extract with precision. The perfect start for those wanting control over their espresso journey.",
        idealUser: "Hands-on Enthusiasts",
        rating: 4.8,
        pros: ["Integrated conical burr grinder", "Precision milk texturing", "Analog pressure gauge"],
        price: "$699.95",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.0L",
        bestFor: "Skill Development",
        easeOfUse: "Intermediate",
        pumpPressure: "15 Bar",
        grinder: "Conical Burr",
        heatingSystem: "Thermocoil",
        image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B00CH9QWOU",
    },
    {
        id: "ninja-12-cup-programmable",
        name: "Ninja 12-Cup Programmable Brewer",
        shortDescription: "High-quality coffee in a large capacity. Custom brew strengths and a Thermal Flavor Extraction technology ensure a rich, full-bodied cup every time.",
        idealUser: "Families and Social Hosts",
        rating: 4.5,
        pros: ["Advanced Thermal Flavor Extraction", "24-hour programmable delay brew", "Mid-brew pause function"],
        price: "$89.99",
        priceRange: "$",
        type: "Drip",
        milkFrother: false,
        capacity: "12 Cups",
        bestFor: "Large Batches",
        easeOfUse: "Very Easy",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07S98411M",
    },
    {
        id: "delonghi-dedica-maestro-plus",
        name: "De'Longhi Dedica Maestro Plus",
        shortDescription: "Professional style in a compact design. The Dedica Maestro Plus offers a premium espresso experience for those with limited counter space.",
        idealUser: "Urban Professionals",
        rating: 4.6,
        pros: ["Compact 6-inch footprint", "My LatteArt steam wand", "Active temperature control"],
        price: "$299.95",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.1L",
        bestFor: "Small Kitchens",
        easeOfUse: "Intermediate",
        image: "https://images.unsplash.com/photo-1517701550927-30cfcb61d4bd?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0CDY85Q2N",
    },
    {
        id: "philips-5400-series",
        name: "Philips 5400 Series Automatic Espresso",
        shortDescription: "Enjoy 12 delicious coffees from fresh beans, including Latte Macchiato, effortlessly. The LatteGo system provides silky-smooth milk froth.",
        idealUser: "Variety Lovers",
        rating: 4.7,
        pros: ["LatteGo easiest milk system ever", "12 coffee varieties at your fingertips", "4 user profiles for personalization"],
        price: "$999.00",
        priceRange: "$$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "1.8L",
        bestFor: "User Customization",
        easeOfUse: "Very Easy",
        image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B08V5MDXDM",
    },
    {
        id: "oxo-brew-8-cup",
        name: "OXO Brew 8-Cup Coffee Maker",
        shortDescription: "Certified by the SCA for meeting rigorous gold-cup standards. Simple operation, elegant design, and exceptional extraction quality.",
        idealUser: "Flavor Purists",
        rating: 4.5,
        pros: ["SCA Certified Gold Cup brewing", "BetterBrew precision control", "Single-serve capability"],
        price: "$199.95",
        priceRange: "$$",
        type: "Drip",
        milkFrother: false,
        capacity: "8 Cups",
        bestFor: "Brewing Standards",
        easeOfUse: "Very Easy",
        image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B0892CHRT3",
    },
    {
        id: "keurig-k-elite",
        name: "Keurig K-Elite Coffee Maker",
        shortDescription: "A versatile single-serve machine that offers a strong brew setting and an iced coffee feature for a perfect cup every time.",
        idealUser: "Busy Individuals",
        rating: 4.6,
        pros: ["Strong brew & iced coffee settings", "Large 75oz water reservoir", "Hot water on demand"],
        price: "$189.99",
        priceRange: "$$",
        type: "Capsule",
        milkFrother: false,
        capacity: "75 oz",
        bestFor: "Speed & Convenience",
        easeOfUse: "Very Easy",
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B078XNWG3N",
    },
    {
        id: "nespresso-vertuoplus",
        name: "Nespresso VertuoPlus by Breville",
        shortDescription: "Utilizes barcode reading technology to automatically adjust brewing parameters for each capsule, ensuring a perfect crema.",
        idealUser: "Espresso Aficionados",
        rating: 4.7,
        pros: ["One-touch brewing system", "Barcode reading for precision", "Adjustable water tank position"],
        price: "$169.00",
        priceRange: "$$",
        type: "Capsule",
        milkFrother: false,
        capacity: "40 oz",
        bestFor: "Rich Crema",
        easeOfUse: "Very Easy",
        image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B01N7T9S77",
    },
    {
        id: "delonghi-la-specialista-arte",
        name: "De'Longhi La Specialista Arte",
        shortDescription: "A compact manual machine that allows you to play the role of the barista with precise control over dose and temperature.",
        idealUser: "Artisan Coffee Lovers",
        rating: 4.8,
        pros: ["Built-in grinder with 8 settings", "Active temperature control", "Professional steam wand"],
        price: "$699.95",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "1.7L",
        bestFor: "Hands-on Experience",
        easeOfUse: "Intermediate",
        image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B09M96V6G2",
    },
    {
        id: "hamilton-beach-flexbrew",
        name: "Hamilton Beach FlexBrew Trio",
        shortDescription: "The ultimate 3-way coffee maker. Brew a full pot, a single cup with grounds, or a single cup with a pod.",
        idealUser: "Budget Conscious Families",
        rating: 4.4,
        pros: ["3-way brewing versatility", "Programmable carafe side", "Fast single-cup brewing"],
        price: "$99.99",
        priceRange: "$",
        type: "Drip",
        milkFrother: false,
        capacity: "12 Cups",
        bestFor: "Affordable Versatility",
        easeOfUse: "Easy",
        image: "https://images.unsplash.com/photo-1517701550927-30cfcb61d4bd?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07LBCMHG5",
    },
    {
        id: "jura-e8-automatic",
        name: "Jura E8 Automatic Coffee Machine",
        shortDescription: "The latest generation of Jura's most successful model. Features a professional aroma grinder and a stunning 2.8 inch color display.",
        idealUser: "Luxury Enthusiasts",
        rating: 4.9,
        pros: ["Pulse Extraction Process (P.E.P.)", "One-touch Lungo function", "Intelligent Water System (I.W.S.)"],
        price: "$2,399.00",
        priceRange: "$$$",
        type: "Automatic",
        milkFrother: true,
        capacity: "1.9L",
        bestFor: "Premium Quality",
        easeOfUse: "Very Easy",
        image: "https://images.unsplash.com/photo-1524350300313-019f39d67d7a?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B08X6K6K5R",
    },
    {
        id: "rancilio-silvia-m",
        name: "Rancilio Silvia M Espresso Machine",
        shortDescription: "A legendary semi-automatic machine built with commercial-grade components. Perfect forThose who want to master the art of traditional espresso.",
        idealUser: "Purists",
        rating: 4.7,
        pros: ["Commercial-grade group head", "Stainless steel case", "Industrial steam wand"],
        price: "$860.00",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.5L",
        bestFor: "Durability",
        easeOfUse: "Expert",
        image: "https://images.unsplash.com/photo-1572442388796-11668a67e53a?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B000109COY",
    },
    {
        id: "gaggia-classic-pro",
        name: "Gaggia Classic Pro",
        shortDescription: "The best entry-level prosumer espresso machine. Features a commercial steam wand and a rapid steam boiler.",
        idealUser: "Budget Baristas",
        rating: 4.6,
        pros: ["Commercial 58mm portafilter", "3-way solenoid valve", "Fast heat-up time"],
        price: "$449.00",
        priceRange: "$$",
        type: "Semi-automatic",
        milkFrother: true,
        capacity: "2.1L",
        bestFor: "Value",
        easeOfUse: "Intermediate",
        image: "https://images.unsplash.com/photo-1580915411954-282cb1b0d780?auto=format&fit=crop&q=80&w=1000",
        latestPriceLink: "https://www.amazon.com/dp/B07KKC4W8N",
    },
];
